x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  ## CORE SERVICES

  traefik:
    image: traefik:latest
    container_name: "rattechan-traefik"
    ports:
      - "80:80"
    networks:
      - rattechan_core
      - rattechan_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik:ro
    env_file:
      - .env
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges:true'
    healthcheck:
      test: 'wget --quiet --spider http://localhost:8082/ping || exit 1'
      interval: '30s'
      timeout: '3s'
      start_period: '5s'
      retries: 3
    logging: *default-logging

  redis:
    image: redis/redis-stack:latest
    container_name: 'rattechan-redis'
    environment:
      RI_PROXY_PATH: "/redis"
    expose:
      - "6379"
    networks:
      - rattechan_core
      - rattechan_proxy
    volumes:
      - rattechan_redis_data:/data
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=rattechan_proxy'
      - "traefik.http.routers.redis.rule=Host(`${SERVER_NAME}`) && PathPrefix(`/redis`)"
      - "traefik.http.routers.redis.entrypoints=http"
      - 'traefik.http.routers.redis.middlewares=no-auth-secured@file'
      - "traefik.http.services.redis.loadbalancer.server.port=8001"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    logging: *default-logging

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: "rattechan-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - rattechan_core
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - rattechan_mosquitto_data:/mosquitto/data
    restart: unless-stopped
    logging: *default-logging

  grafana:
    image: grafana/grafana:latest
    container_name: "rattechan-grafana"
    networks:
      - rattechan_core
      - rattechan_proxy
    volumes:
      - rattechan_grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: "redis-datasource,grafana-mqtt-datasource"
      GF_SERVER_DOMAIN: ${SERVER_NAME}
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=rattechan_proxy'
      - "traefik.http.routers.grafana.rule=Host(`${SERVER_NAME}`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=http"
      - 'traefik.http.routers.grafana.middlewares=no-auth-secured@file'
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    security_opt:
      - 'no-new-privileges:true'
    logging: *default-logging

  ## LOGGING SERVICES

  loki:
    image: grafana/loki:latest
    container_name: "rattechan-loki"
    ports:
      - "3100:3100"
    networks:
      - rattechan_core
      - rattechan_proxy
    volumes:
      - rattechan_loki_data:/etc/loki:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=rattechan_proxy'
      - "traefik.http.routers.loki.rule=Host(`${SERVER_NAME}`) && PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.entrypoints=http"
      - 'traefik.http.routers.loki.middlewares=no-auth-secured@file'
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    logging: *default-logging

  promtail:
    image: grafana/promtail:latest
    container_name: "rattechan-promtail"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro,rshared # Set as read-only since Promtail only reads logs
      - ./promtail/config.yml:/etc/promtail/config.yml:ro  # Ensure config is read-only
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for metadata
      - rattechan_promtail_data:/etc/promtail  # Volume for storing positions
    networks:
      - rattechan_core
    restart: unless-stopped
    logging: *default-logging

  ## DATA PERSISTENCE SERVICES

  influxdb:
    image: influxdb:latest
    container_name: "rattechan-influxdb"
    expose:
      - "8086"
    networks:
      - rattechan_core
    volumes:
      - rattechan_influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=rattechan_org
      - DOCKER_INFLUXDB_INIT_BUCKET=rattechan_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped
    logging: *default-logging


  telegraf:
    image: telegraf:latest
    container_name: "rattechan-telegraf"
    networks:
      - rattechan_core
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_BUCKET=rattechan_bucket
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
      - INFLUX_ORG=rattechan_org
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped
    logging: *default-logging

  ## SENSOR SERVICES
  controller:
    build:
      context: controller-rpi
      dockerfile: Dockerfile
    container_name: "controller-rpi"
    networks:
      - rattechan_core
    environment:
      REDIS_URL: redis://secretum-redis:6379
      GPIO_ENABLED: 0
    volumes:
      - /dev/gpiomem0:/dev/gpiomem0
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=secretum_proxy'
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=Host(`${SERVER_NAME}`) && PathPrefix(`/app`)"
      - 'traefik.http.routers.app.middlewares=no-auth-secured@file'
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.app.stripprefix.prefixes=/app"
    restart: 'unless-stopped'
    privileged: true

  ## DEBUGGING SERVICES

  mqttx:
    image: emqx/mqttx-web
    container_name: "rattechan-mqttx"
    profiles:
      - debug
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=rattechan_proxy'
      - "traefik.http.routers.mqttx.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.mqttx.entrypoints=http"
      - 'traefik.http.routers.mqttx.middlewares=no-auth-secured@file'
      - "traefik.http.services.mqttx.loadbalancer.server.port=80"
    networks:
      - rattechan_core
      - rattechan_proxy
    restart: unless-stopped
    logging: *default-logging

  fake-data-generator:
    container_name: "rattechan-fake-data-generator"
    profiles:
      - debug
    build:
      context: fake-data-generator
      dockerfile: Dockerfile
    networks:
      - rattechan_core
    environment:
      MQTT_BROKER: "mosquitto"
      MQTT_PORT: 9001
      MQTT_TOPIC: "generator"
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging: *default-logging

volumes:
  rattechan_redis_data:
  rattechan_influxdb_data:
  rattechan_mosquitto_data:
  rattechan_grafana_data:
  rattechan_loki_data:
  rattechan_promtail_data:

networks:
  rattechan_core:
  rattechan_proxy:
    external: true