#!/bin/bash
# This script is invoked by the mybinder.org service which can detect,
# display and execute any .ipynb Jupyter Notebook in the repository.
set -e
# We reuse the requirements from the documentation project
VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
