stateDiagram-v2
    Exploring: Exploration Policy
    Swiping: Swiping Policy
    Tunneling: Tunneling Policy
    Retrieval: Retrieval Policy

    [*] --> Exploring

    Exploring --> Swiping : 0-->1 Contacts & <br> Spline Defined
    Exploring --> Tunneling : 0-->2 <br>Contacts
    Tunneling --> Exploring : 2-->0 <br>Contacts
    Tunneling --> Swiping : 2-->1 <br>Contacts
    Swiping --> Retrieval : 1-->0 <br>Contacts
    Retrieval --> Exploring : 0-->1 Contacts & <br> Edge Retrieved
    Swiping --> Tunneling : 1-->2 <br>Contacts
