apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      auth: true
    secureJsonData:
      password: ${REDIS_PASSWORD}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
